#!/usr/bin/env python3
import argparse
import os
import sqlite3
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from db import connect as connect_database, database_url
from scripts.build_database import create_schema, database_has_schema


DEFAULT_SQLITE_PATH = ROOT / "data" / "cd_catalog.sqlite"

TABLES = [
    "api_cache",
    "albums",
    "artists",
    "musicbrainz_metadata",
    "tracks",
    "album_genres",
    "cover_art",
    "album_service_status",
    "external_metadata",
    "users",
    "auth_sessions",
    "scan_events",
    "app_settings",
]

IDENTITY_TABLES = [
    "albums",
    "artists",
    "tracks",
    "album_genres",
    "cover_art",
    "external_metadata",
    "scan_events",
]


def sqlite_tables(conn: sqlite3.Connection) -> set[str]:
    return {
        row["name"]
        for row in conn.execute(
            """
            SELECT name
            FROM sqlite_master
            WHERE type = 'table'
            """
        ).fetchall()
    }


def sqlite_columns(conn: sqlite3.Connection, table: str) -> list[str]:
    return [row["name"] for row in conn.execute(f"PRAGMA table_info({table})").fetchall()]


def postgres_columns(conn: Any, table: str) -> list[str]:
    return [
        row["column_name"]
        for row in conn.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = ?
            ORDER BY ordinal_position
            """,
            (table,),
        ).fetchall()
    ]


def table_exists_postgres(conn: Any, table: str) -> bool:
    row = conn.execute(
        """
        SELECT EXISTS (
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = 'public' AND table_name = ?
        ) AS exists
        """,
        (table,),
    ).fetchone()
    return bool(row and row["exists"])


def clear_postgres_tables(conn: Any) -> None:
    existing = [table for table in TABLES if table_exists_postgres(conn, table)]
    if existing:
        conn.execute(f"TRUNCATE {', '.join(existing)} RESTART IDENTITY CASCADE")


def ensure_app_tables(conn: Any) -> None:
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS auth_sessions (
            token_hash TEXT PRIMARY KEY,
            username TEXT NOT NULL,
            created_at TEXT NOT NULL,
            last_seen TEXT NOT NULL
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS users (
            username TEXT PRIMARY KEY,
            password_hash TEXT NOT NULL,
            is_admin INTEGER NOT NULL DEFAULT 0,
            is_editor INTEGER NOT NULL DEFAULT 0,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS scan_events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT NOT NULL,
            created_at TEXT NOT NULL,
            payload_json TEXT NOT NULL
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS app_settings (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )
    conn.execute("CREATE INDEX IF NOT EXISTS idx_scan_events_user_id ON scan_events(username, id)")


def copy_table(sqlite_conn: sqlite3.Connection, pg_conn: Any, table: str) -> int:
    if table not in sqlite_tables(sqlite_conn) or not table_exists_postgres(pg_conn, table):
        return 0
    sqlite_column_names = sqlite_columns(sqlite_conn, table)
    pg_column_names = postgres_columns(pg_conn, table)
    columns = [column for column in sqlite_column_names if column in pg_column_names]
    if not columns:
        return 0

    rows = sqlite_conn.execute(f"SELECT {', '.join(columns)} FROM {table}").fetchall()
    if not rows:
        return 0

    placeholders = ", ".join("?" for _ in columns)
    quoted_columns = ", ".join(columns)
    pg_conn.executemany(
        f"INSERT INTO {table} ({quoted_columns}) VALUES ({placeholders}) ON CONFLICT DO NOTHING",
        [tuple(row[column] for column in columns) for row in rows],
    )
    return len(rows)


def reset_identity_sequence(conn: Any, table: str) -> None:
    if not table_exists_postgres(conn, table):
        return
    row = conn.execute(f"SELECT COALESCE(MAX(id), 0) + 1 AS next_id FROM {table}").fetchone()
    conn.execute(f"ALTER TABLE {table} ALTER COLUMN id RESTART WITH {int(row['next_id'])}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Migrate the old SQLite catalog database into Postgres.")
    parser.add_argument("--sqlite", type=Path, default=Path(os.environ.get("SQLITE_DATABASE_PATH", DEFAULT_SQLITE_PATH)))
    parser.add_argument("--database-url", default=database_url())
    parser.add_argument("--recreate", action="store_true", help="Drop and recreate the Postgres catalog tables before migrating.")
    parser.add_argument("--append", action="store_true", help="Append into existing Postgres tables instead of truncating them first.")
    args = parser.parse_args()

    sqlite_path = args.sqlite.expanduser()
    if not sqlite_path.exists():
        raise SystemExit(f"SQLite database not found: {sqlite_path}")
    if args.recreate and args.append:
        raise SystemExit("--recreate and --append cannot be used together.")

    sqlite_conn = sqlite3.connect(sqlite_path)
    sqlite_conn.row_factory = sqlite3.Row
    try:
        with connect_database(args.database_url) as pg_conn:
            if args.recreate or not database_has_schema(pg_conn):
                create_schema(pg_conn)
                pg_conn.commit()
            ensure_app_tables(pg_conn)
            if not args.append:
                clear_postgres_tables(pg_conn)

            total = 0
            for table in TABLES:
                count = copy_table(sqlite_conn, pg_conn, table)
                total += count
                print(f"{table}: {count} rows")

            for table in IDENTITY_TABLES:
                reset_identity_sequence(pg_conn, table)
            pg_conn.commit()
            print(f"Migrated {total} rows from {sqlite_path} to Postgres.")
    finally:
        sqlite_conn.close()


if __name__ == "__main__":
    main()
